services:

  sharex-spring:
    image: amazoncorretto:21-alpine-jdk
    container_name: sharex-spring
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - APP_SECURITY_API_KEY=changeme
      - APP_RATE_LIMIT_ACTION=50
      - APP_RATE_LIMIT_WRONG_API_KEY=1
      - APP_PUBLIC_UPLOADED_FILES=https://YOUR_DOMAIN/share/u/
      - APP_PUBLIC_SHORTENED_URLS=https://YOUR_DOMAIN/share/s/
      - APP_FILE_UPLOAD_DIRECTORY=./uploads/
      - APP_LIMITS_FILE_UPLOADER_GENERATED_NAME_LENGTH=8
      - APP_LIMITS_FILE_UPLOADER_SIZE=-1
      - APP_LIMITS_URL_SHORTENER_GENERATED_NAME_LENGTH=4
      - SERVER_PORT=9007
    ports:
      - "9007:9007"
    command: ["java", "-jar", "sharex-spring-0.0.6-SNAPSHOT.jar"]
    restart: unless-stopped
    user: "1000:1000"
    #networks:
    #  - shared-nginx

#networks:
#  shared-nginx:
#    external: true
