server:
  port: 9007

spring:
  datasource:
    url: jdbc:postgresql://sharex_database:5432/sharex
    driverClassName: org.postgresql.Driver
    username: sharex_user
    password: sharex_password
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

app:
  security:
    api-key: "changeme"
    rate-limit-action: 50
    rate-limit-wrong-api-key: 1

  public:
    uploaded-files: "http://localhost:9007/share/u/"
    shortened-urls: "http://localhost:9007/share/s/"

  file:
    upload-directory: "./uploads/"

  # Generated names table:
  # (length : number of unique entries)
  # 4       : 14,776,336
  # 6       : 56,800,235,584
  # 8       : 218,340,105,584,896
  # 10      : 839,299,365,868,340,224
  # 12      : 3,226,266,762,397,899,821,056
  # 14      : 12,401,769,434,657,526,912,139,264
  # 16      : 47,672,401,706,823,533,450,263,330,816
  limits:
    file-uploader:
      generated-name-length: 8
      # `size` is in KBytes
      # value of `-1` defaults to 1024MB (spring.servlet.multipart.max-file-size)
      size: 51200
    url-shortener:
      generated-name-length: 4

  caching:
    ttl: 60 # in minutes
    size: 100 # items in cache