name: Build GraalVM Native Image and JAR

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build-jar:
    name: Build JAR with Corretto
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build JAR
        run: ./gradlew bootJar
        
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Rename JAR
        run: |
          cd build/libs/
          mv *.jar sharex-spring-${GITHUB_REF#refs/tags/}-default.jar
        if: startsWith(github.ref, 'refs/tags/')
        
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: sharex-spring-jar
          path: build/libs/sharex-spring-*-default.jar

  build-native:
    name: Native Build with GraalVM
    strategy:
      matrix:
        architecture: [aarch64, amd64]
        include:
          - architecture: aarch64
            runner: ubuntu-latest
            artifact-name: sharex-spring-arm64
          - architecture: amd64
            runner: ubuntu-latest
            artifact-name: sharex-spring-x86_64
    
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          architecture: ${{ matrix.architecture }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Native Image
        run: ./gradlew nativeCompile
        
      - name: Rename executable for architecture
        run: |
          cd build/native/nativeCompile/
          mv sharex-spring sharex-spring-${GITHUB_REF#refs/tags/}-${{ matrix.architecture }}
        if: startsWith(github.ref, 'refs/tags/')
        
      - name: Upload Native Image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: build/native/nativeCompile/sharex-spring-*-${{ matrix.architecture }}

  create-release:
    name: Create Release
    needs: [build-jar, build-native]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/sharex-spring-jar/sharex-spring-*-default.jar
            artifacts/sharex-spring-arm64/sharex-spring-*-aarch64
            artifacts/sharex-spring-x86_64/sharex-spring-*-amd64
          name: ${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}