name: Build GraalVM Native Image

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    name: Native Build with GraalVM
    strategy:
      matrix:
        architecture: [aarch64, amd64]
        include:
          - architecture: aarch64
            runner: ubuntu-latest
            artifact-name: sharex-spring-arm64
          - architecture: amd64
            runner: ubuntu-latest
            artifact-name: sharex-spring-x86_64
    
    runs-on: ${{ matrix.runner }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          architecture: ${{ matrix.architecture }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Native Image
        run: ./gradlew --no-daemon nativeCompile
        
      - name: Upload Native Image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact-name }}
          path: build/native/nativeCompile/sharex-spring*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/native/nativeCompile/*
          name: Release ${{ env.VERSION }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}