name: Quick Tests

on:
  push:
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create .env file
        run: |
          echo "JWT_SECRET=" > .env
          echo "SPRING_SECURITY_PASSWORD=" >> .env

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.sha }}
          path: |
            build/reports/tests/
            build/test-results/

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit